apiVersion: apps/v1
kind: Deployment
metadata:
  name: game1000
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game1000
  template:
    metadata:
      labels:
        app: game1000
    spec:
      containers:
        - name: game1000
          image: xyz/game1000:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: jdbc:postgresql://postgres:5432/db
            - name: DB_USER
              value: postgres
            - name: DB_PASS
              value: postgres